### PR TITLE
Profile- completed implementing the entity, ProfileController, ProfileEditInputBoundary, ProfileEditUseCase, ProfileFactory, ProfileInModel, ProfileOutModel, ProfileUpdateOutputBoundary; just need to complete ProfilePresenter based on UI

### PR DESCRIPTION
**Pull request by XiWang16**

### CODE REVIEW

**Review by lancenigel — APPROVED** [review]

**Review by tankenji — APPROVED** [review]

**Review by tankenji — APPROVED** [review]

**Review by tankenji — COMMENTED** [review]
Test comment. Please ignore.

**Review by SanzSS — APPROVED** [review]

**Review by lancenigel — COMMENTED** [review]
For the Profile, I like that you reformatted your code to adhere to clean architecture. Renaming your classes, for example from ProfileBasicInfoEditUseCase to ProfileEditUseCase, helps break down complexity. Your code goes from interface adapters (Presenter/Controller) to application business rules (your use case) to the enterprise business rules (entities). In your ProfileFactory class, you should consider looking over the create method. I like that you implemented a Factory Design pattern but there are some improvements that can be made. I believe it should be static as the ProfileEditUseCase calls upon it.

Here is an example of how factory design patterns are implemented: https://levelup.gitconnected.com/learn-the-factory-pattern-in-a-clean-simple-animal-application-35fa23aa40e2

**Comment by XiWang16** [comment]
This is my most significant pull request because it includes the bulk of my code and structures the profile feature according to CA and SOLID principles. I modelled my code after Jiheon’s and utilized interfaces and In/OutModels to increase my code’s flexibility and decrease dependency. I also made sure my Profile feature performs only one function: store all the users personal information and provides editing function when necessary. There’s dependency inversion as only the outer layers calls on methods of the inner ones.

**Comment by karenrni** [comment]
Overall, Profile contains clearly named classes and methods and adheres to clean architecture as well as SOLID principles. For example, the dependency inversion in the use of ProfileEditUseCase as it implements ProfileEditInputBoundary. 

Although the method names are clear and understanding their function is mostly straightforward, I would suggest adding more java docs as there are many different methods in each class and many different feature classes interact with them. 

Also, in the Profile class there are some UI components such as JList & JComboBox. I suggest moving the UI components into a UI class so that the entity layer and frameworks/drivers layer are kept separate. 

Lastly, to be consistent with the other features, consider creating packages and organizing profile classes further, such as by layer.

**Pull request merged**
