### PR TITLE
Renamed all uppercase package names to lowercase.

### PR DESCRIPTION
**Pull request by HuakunShen**
This `fix-package-name` branch is created from `main` branch.

What I did was simply renaming all of your package names with uppercase letters to lowercase package names.

There are errors in your `main` branch, so I can't verify if the code runs. 
**TODO**: So you should better go to the branch, fix the error and see if it complies and runs. 
Reminder: your `main` branch should be always stable, compilable and runnable. 

**TODO**: Review the files modified in this PR and to see if there is anything you don't expect.

The reason I do this for you is because of case insensitive file system of Mac and Windows. It's very hard to fix it on both Mac and Windows, so I tried to fix it for you using a Linux OS.

On GitHub, you can see both `Swipe` and `swipe`, but on Mac or Windows, you can only see one of the folders. That's the problem.

**TODO**: Once the PR merges to `main` branch, everyone in the team should merge the latest version of `main` to their feature branches to avoid future problem.

### CODE REVIEW

**Comment by HuakunShen** [comment]
@XiWang16 Merge this branch to your branch, or merge from `main` to your feature branch after this PR is merged to `main`, then your merge conflict should be resolved. 
Let me know if it works.

**Review by karenrni — APPROVED** [review]

**Review by XiWang16 — COMMENTED** [review]
I added some imports that might have been deleted by accident rather than changed to lowercase. Please review if all the files are now ready for pulling and merging. Other than that, thanks Huakun for making the alterations!

**Review by XiWang16 — DISMISSED** [review]

**Review by lancenigel — DISMISSED** [review]

**Comment by HuakunShen** [comment]
After merging this PR and merging `main` to your feature branch, check if you have duplicate package names with uppercase letters on GitHub website. The duplicate package names are not visible on Mac or Windows computer.

If there are still duplicate package names, let me know. You should be able to fix it using GitHub's web editor, see https://youtu.be/PQg9OB1JA9A?t=39 . Make sure you are on the feature branch when using this editor. Committed changes are pushed automatically.

**Comment by HuakunShen** [comment]
I noticed that there were 2 `useCases` packages not renamed. Just renamed them to `use_cases`.

**Review by XiWang16 — APPROVED** [review]

**Review by nina-huangg — APPROVED** [review]

**Comment by XiWang16** [comment]
We were able to pull and merge all the package name changes and there should be no duplicates on GitHub. Thanks again for helping us, Huakun!!

**Pull request merged**
